app:
  name: anuglar2-spring-jwt

jwt:
  header: Authorization
  expires_in: 600 # 10 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN

logging:
  level:
    org.springframework.web: ERROR
    com.bfwg: DEBUG
spring:
  jpa:

    show-sql: true  
    hibernate.ddl-auto: create-drop
  datasource.platform: postgres 

 
server.port: 8095

logging.file: application.log
